# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimmed_link', models.CharField(max_length=8, unique=True)),
                ('original_link', models.TextField(unique=True)),
                ('date_trimmed', models.DateTimeField(auto_now_add=True, verbose_name='date trimmed')),
            ],
        ),
    ]
