# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trim_my_links', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='date_trimmed',
            new_name='timestamp',
        ),
    ]
